### ISSUE TITLE
Unimod doesn't work with SQLAlchemy 1.4.2

### ISSUE THREAD

**Issue by levitsky** [levitsky/pyteomics#31]
The unimod test fails to start with this error on latest SQLAlchemy 1.4.2:

```
ERROR: setUpClass (__main__.UnimodTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lev/py/pyteomics/tests/test_unimod.py", line 12, in setUpClass
    cls.handle = unimod.Unimod()
  File "/home/lev/py/pyteomics/pyteomics/mass/unimod.py", line 688, in __init__
    self.session = load(_unimod_xml_download_url)
  File "/home/lev/py/pyteomics/pyteomics/mass/unimod.py", line 655, in load
    for model in Base._decl_class_registry.values():
AttributeError: type object 'Base' has no attribute '_decl_class_registry'
```

**Comment by mobiusklein** [comment]
SQLAlchemy is starting to migrate to a new architecture. I just started seeing breakages on CI for 1.4 on other projects. I'll get started on this at least, it should be easier to fix.
